"""Optional web visual search fallback (provider-based)."""

from app.services.web_visual_search import (
    PROVIDER_DISPLAY_NAMES,
    PROVIDER_SEARCHAPI,
    PROVIDER_SERPAPI,
    UNAUTHORIZED_LENS_MESSAGE,
    WEB_VISUAL_SEARCH_SOURCE,
    LensSearchCandidate,
    LensSearchError,
    LensSearchQuery,
    LensSearchResult,
    WebVisualSearchProvider,
    build_lens_search_query,
    build_normalized_crop_parameter,
    get_web_visual_search_provider,
    parse_lens_candidates,
    redact_sensitive_text,
    redact_sensitive_url,
    resolve_lens_image_url,
    search_artwork_with_lens,
    unauthorized_lens_message,
)

__all__ = [
    "PROVIDER_DISPLAY_NAMES",
    "PROVIDER_SEARCHAPI",
    "PROVIDER_SERPAPI",
    "UNAUTHORIZED_LENS_MESSAGE",
    "WEB_VISUAL_SEARCH_SOURCE",
    "LensSearchCandidate",
    "LensSearchError",
    "LensSearchQuery",
    "LensSearchResult",
    "WebVisualSearchProvider",
    "build_lens_search_query",
    "build_normalized_crop_parameter",
    "get_web_visual_search_provider",
    "parse_lens_candidates",
    "redact_sensitive_text",
    "redact_sensitive_url",
    "resolve_lens_image_url",
    "search_artwork_with_lens",
    "unauthorized_lens_message",
]
